name: Release
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
          platforms: 'linux/amd64, linux/arm64, darwin/amd64, windows/amd64'
          package: ''
          name: 'document-translator-cli'
          compress: 'false'
          dest: 'dist'
    - name: sha256sum
      run: |
        for FILE in dist/*; 
          do sha256sum $FILE > ${FILE:4}.sha256; 
        done
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/document-translator-cli-linux-amd64
          dist/document-translator-cli-linux-arm64
          dist/document-translator-cli-darwin-amd64
          dist/document-translator-cli-windows-amd64.exe
          *.sha256